### PR TITLE
Custom formatter for LineChartAxis for dates

### LINKED ISSUE #105: Wrong datetime labels on line chart visualisation
My local timezone: UTC+2H

Open Turnilo, change visualization to line-chart, select 7 days period and look at X axis labels, 02 AM is displayed instead of days.

[wrong labels](http://localhost:9090/#wiki/3/N4IgbglgzgrghgGwgLzgFwgewHYgFwhLYCmAtAMYAWcATmiADQgYC2xyOx+IAomuQHoAqgBUAwoxAAzCAjTEaUfAG1QaAJ4AHLgVZcmNYlO57JegAoKsAEyV5VIazBrosuAuYCMAETNadhOjEUPRMIcSa+KQA7AC+ALoJYZpIaHYOGtomEGyS1jnE2FBu2blMAOYu2DAItBAa3OYingASklCYdPighsa6BXkQhuQYONxwUOSF+djlILFMSCz1+NUICEkgbBPOwd0g0ACyNRj4UohQxGEQswgB1sRycJIsJxAqIOSYMNihjo9oZ5MOBgcoAfQeT0kcGsD2sIESTE0NxI1m8BSKbnSn2o2BICEk2DgbCgmjgU0k0AASpgAEaYejxJEo4jWADKnXoBEhgMkd3K01WNQQTEoEHKlCQEq5aw2QA==)

When timezone is changed to Europe/Paris (UTC+2H) days are displayed on X axis as expected.

[correct labels](http://localhost:9090/#wiki/3/N4IgbglgzgrghgGwgLzgFwgewHYgFwhLYCmAtAMYAWcATmiADQgYC2xyOx+IAojDZgAOxAPQAFWtEYgAZhARpiNKPgDaoNAE9h3VlyY1iM3RDbS9YpVgAmKvOpDX+6LLgJiAjABFz2rgQR0Yih6JhDiQXxSAHYAXwBdBLDBJDQ7By0dAj1pa1NibChXEzMmAHMaOGwYQJoILW4xABUPAAlpKEw6fFBDY2z83IhDcgwcbjgocgK87DKQWKYkFnr8aoQEJJA2Sf5gnpBoAFkajHwZRChiMIg5hH9HYgU4aRZTiDUQckwYbFDH57SOBgMoAfWsTzQLyYcGsEOsIESTEEtxI1i8+UKrnSX2o2BICGk2DgbCggjg02k0AASpgAEaYejxZGo4jWADKXXoBAhgKWxDKMzWNQQTEoEDKlCQku5602QA=)

### PR DESCRIPTION
**Pull request by adrianmroz**
Closes #105

### CODE REVIEW

File: src/client/components/line-chart-axis/line-chart-axis.tsx [hunk 1]
```diff
@@ -20,58 +20,78 @@ import * as d3 from "d3";
...
 import { Stage } from "../../../common/models/stage/stage";
+import { Unary } from "../../../common/utils/functional/functional";
 import { roundToHalfPx } from "../../utils/dom/dom";
 import "./line-chart-axis.scss";
 
 const TICK_HEIGHT = 5;
 const TEXT_OFFSET = 12;
-const floatFormat = d3.format(".1f");
+
+type AxisScale = d3.time.Scale<Date, number> | d3.time.Scale<number, number>;
```
Comment (piter75) [inline src/client/components/line-chart-axis/line-chart-axis.tsx]: For consideration.
We could **probably** extract AxisTick or Tick type = Date | number, and then use it here as d3.time.Scale<Tick, number> and in all following lines where "Date | number" is referenced.

I haven't checked it but should be possible in TypeScript.

Comment (adrianmroz) [reply src/client/components/line-chart-axis/line-chart-axis.tsx]: But we don't want to have scale that accepts Date or number. We want scale for Date or scale for number.
