### PR TITLE
Handle filters for multivalue dimensions when has also split

### LINKED ISSUE #455: Filter out multi-value dimension
Multi-value dimensions queries return unexpected results and additional filtered dimension spec should be applied (using the same predicate as in regular filter).

Instead of the following query (groupBy as an example):

```
{
  "queryType": "groupBy",
  "dataSource": "test",
  "intervals": [
    "1970-01-01T00:00:00.000Z/3000-01-01T00:00:00.000Z"
  ],
  "filter": {
    "type": "selector",
    "dimension": "tags",
    "value": "t3"
  },
  "granularity": {
    "type": "all"
  },
  "dimensions": [
    {
      "type": "default",
      "dimension": "tags",
      "outputName": "tags"
    }
  ],
  "aggregations": [
    {
      "type": "count",
      "name": "count"
    }
  ]
}
```

The following query should be generated:

```
{
  "queryType": "groupBy",
  "dataSource": "test",
  "intervals": [
    "1970-01-01T00:00:00.000Z/3000-01-01T00:00:00.000Z"
  ],
  "filter": {
    "type": "selector",
    "dimension": "tags",
    "value": "t3"
  },
  "granularity": {
    "type": "all"
  },
  "dimensions": [
    {
      "type": "listFiltered",
      "delegate": {
        "type": "default",
        "dimension": "tags",
        "outputName": "tags"
      },
      "values": ["t3"]
    }
  ],
  "aggregations": [
    {
      "type": "count",
      "name": "count"
    }
  ]
}
```

See also:
https://druid.apache.org/docs/latest/querying/multi-value-dimensions.html

### PR DESCRIPTION
**Pull request by adrianmroz**
Fixes #455

### CODE REVIEW

File: src/common/utils/query/visualization-query.ts [hunk 1]
```diff
@@ -92,6 +93,16 @@ function applyCanonicalLengthForTimeSplit(split: Split, dataCube: DataCube) {
   };
 }
 
+function applyListFilterExpression(split: Split, dimension: Dimension, { filter, dataCube }: Essence) {
+  const { name } = dimension;
+  const { type } = dataCube.attributes.find(a => a.name === name);
```
Comment (adrianmroz) [inline src/common/utils/query/visualization-query.ts]: Maybe we should propagate attribute type to Dimension record?

File: src/common/utils/query/visualization-query.ts [hunk 2]
```diff
@@ -92,6 +93,16 @@ function applyCanonicalLengthForTimeSplit(split: Split, dataCube: DataCube) {
...
+  return (query: Expression) => {
+    if (type !== "SET/STRING") return query;
```
Comment (adrianmroz) [inline src/common/utils/query/visualization-query.ts]: What about other "SET/*" types?

File: src/common/utils/query/visualization-query.ts [hunk 3]
```diff
@@ -92,6 +93,16 @@ function applyCanonicalLengthForTimeSplit(split: Split, dataCube: DataCube) {
...
+    const clause = filter.clauseForReference(name);
+    return query.filter(toExpression(clause, dimension));
```
Comment (adrianmroz) [inline src/common/utils/query/visualization-query.ts]: We duplicate filter there (we added the same filter at top level)!

File: src/common/utils/query/visualization-query.ts (hunk 1 above)
Comment (adrianmroz) [reply src/common/utils/query/visualization-query.ts]: And what about data cubes without introspection? Are attributes set correctly?

Comment (adrianmroz) [reply src/common/utils/query/visualization-query.ts]: Resolved
