### PR TITLE
Check if measure value is finite number before formatting.

### LINKED ISSUE #389: Crash with Percent of Parent measure selected
Turnilo crashes when mouse is over the `war` channel point (the red circle in the screenshot below). Turnilo verison is git commit c4d12bc.

Screenshot_Turnilo

```
TypeError: s is null
    D formatting.js:733
    i formatting.js:106
    r formatting.js:71
    format formatting.js:769
    value numbro.js:40
    formatFnFactory series-format.ts:45
    formatValue concrete-series.ts:94
    colorEntries line-chart.tsx:428
    mapTruthy functional.ts:44
    reduce (index):359
    mapTruthy functional.ts:43
    renderChartBubble line-chart.tsx:420
    renderChart line-chart.tsx:661
    measureCharts line-chart.tsx:804
    map (index):286
    renderInternals line-chart.tsx:803
    render base-visualization.tsx:177
    React 14
    dispatchEvent (index):1018
```
```
The above error occurred in the <LineChart> component:
    in LineChart (created by CubeView)
    in div (created by CubeView)
    in div (created by CubeView)
    in div (created by CubeView)
    in div (created by CubeView)
    in div (created by CubeView)
    in CubeView (created by TurniloApplication)
    in main (created by TurniloApplication)
    in TurniloApplication

React will try to recreate this component tree from scratch using the error boundary you provided, TurniloApplication.
```

Reproduce link: http://127.0.0.1:9090/#wiki/4/N4IgbglgzgrghgGwgLzgFwgewHYgFwhLYCmAtAMYAWcATmiADQgYC2xyOx+IAomuQHoAqgBUAwoxAAzCAjTEaUfAG1QaAJ4AHLgVZcmNYlO57JegAoKsAEyV5VIazBrosuAuYCMAEUlR5mviknkwa2twI6MT+IAC+ALoJTFCaSGh2DmE6IP40ENgA5pLWEGzYUG7cVHDYJAh+mHT4oIbGBNW1xPWhWtklZRU4xRCG5BhDBNbR5MTYJYVxTEgsEPR42DAICLEMar0mpfqOh+WVuoeSBS4bkXka3OYingASDU14LUYHbGb7kyeDXBMEqjcbuEBwKAzOb5Io7QilVb4G7beLJKzRFSfKQKWYzbhwaxTaySKSNFjoZrMP6OIxwTb0JhgRAwbKLanhAjEAAemkMUEBkh5fOigo+IEw2hcYO4UuhaAA+pgpArNLRZvRYkkQJp8iRrN4AW4MiAOnVJNg4GwUnB8UxoAAlTAAI0w9DROr1xGsAGVGmsIUTvQrVQp5UqVWrDNhGYRiAVZiTxf1ZmLTdROt0ESs1gBWJkszHrTYIJjUKAAORL+CkiCgxHhlAgBUoSBbaxRsSAA

### PR DESCRIPTION
**Pull request by adrianmroz**
Closes #389

### CODE REVIEW

File: src/common/utils/general/general.ts [hunk 1]
```diff
@@ -40,6 +40,10 @@ export function isBlank(str: string): boolean {
   return str.length === 0;
 }
 
+export function isFiniteNumber(n: number): boolean {
+  return typeof n === "number" && isFinite(n) && !isNaN(n);
```
Comment (fpoon) [inline src/common/utils/general/general.ts]: is a typeof operator necessary here?

Comment (adrianmroz) [reply src/common/utils/general/general.ts]: plywood declares it's numeric values as numbers but it sometimes returns `null` (it's not compiled with `--strict`) so we need check to be sure

the case was with formulas and division - when denominator was zero, plywood returned null
